### PR TITLE
fix: Production credentials

### PR DESCRIPTION
**Pull request by davegudge**
Utilise multi environment credentials introduced via rails/rails#33521

This change fixes an issue when setting up the developer environment. Executing `bin/setup` generated the following error:

```
== Preparing database ==
rails aborted!
ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
railsdevs.io/config/environment.rb:5:in `<top (required)>'

Caused by:
OpenSSL::Cipher::CipherError:
railsdevs.io/config/environment.rb:5:in `<top (required)>'
```

This due to '_public_' developers not having access to `config/master.key`. 

Following this change, 'owner' developers should update `config/master.key` to `config/credentials/production.key`

```bash
mv config/master.key config/credentials/production.key
```

ensuring that the renamed key is not committed to version control (which should be ensured by the change to `.gitignore`).

Resources:
---

* rails/rails#33521
* https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html

### CODE REVIEW

**Comment by davegudge** [comment]
@joemasilotti If this change is accepted, you'll need to tweak upon deployment. I think you're hosting on Heroku, so this link should help: https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html#storing-encryption-key-in-environment-variables

**Comment by davegudge** [comment]
I'll have to rebase this PR to accommodate for 80b1a2169bdd0c5613b9cf5efb19aeac17f83ee7

**Comment by davegudge** [comment]
> I'll have to rebase this PR to accommodate for 80b1a21

Done.

**Comment by joemasilotti** [comment]
Maybe I'm missing something here... but why is this needed if we are only using production credentials?

I just fresh-cloned the repo and ran `bin/setup` with no issues.

**Comment by davegudge** [comment]
Oh sorry @joemasilotti, I've figured out what's happening _on my machine_. 

Some of the projects I work on use a script to generate a `.env` file to set any environment variables that are required to run the project. This includes reading the value in `config/master.key` and setting the `RAILS_MASTER_KEY` environment variable. 

Prior to setting up `railsdevs.io`, I had clearly `cd`'ed into another project, so the `RAILS_MASTER_KEY` was set in _that_ terminal session, thus when attempting to execute `bin/setup`, the `RAILS_MASTER_KEY` from _another_ project was used, resulting in `ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage`.

**Comment by joemasilotti** [comment]
Ahh, that makes sense! Thanks for following up.

**Pull request closed without merging**
