### PR TITLE
feat: Cover image for developers

### PR DESCRIPTION
**Pull request by jacobdaddario**
This is a WIP. Part way through implementing behavior right now. Need to add some validations and then implement drag and drop behavior, which will be a novel thing for me. That may take some time, so I'm making this PR now to show the WIP.

Additionally, for now this includes the commits from #20, but I'll rebase this branch on `main` whenever the basic ActiveStorage stuff gets merged in.

### CODE REVIEW

**Comment by joemasilotti** [comment]
@jacobdaddario, feel free to merge or rebase now. I think using the same conventions I added (spinner vs. progress bar) should work fine for this, too.

**Comment by jacobdaddario** [comment]
Mind the commit history... The rebase got messy and for some reason `HEAD` tags some how got merged in on these commits. I should've kicked off `ffa02b3` and `63588fb`. Regardless, the repo is in the proper state now, the commits just read weirdly.

**Comment by joemasilotti** [comment]
Nice! Is this ready for review? Also, feel free to merge in master (instead of rebasing) since the commit history will be squashed.

**Comment by jacobdaddario** [comment]
Not quite. Missing one piece. We can chat about it this evening.

**Comment by joemasilotti** [comment]
Looking forward to it!

**Comment by jacobdaddario** [comment]
Had some time during breakfast, so I slapped together what we talked about doing. Mostly just had to tear out the Stimulus behavior from the first attempt, and the rest came together pretty easily. Ended up rebasing to make merging for you easier and to clean up the crazy commit history for anyone who looks at this PR down the road.

I know some people are opposed to re-writing history like that, but I've come to really enjoy the rebase workflow. Let me know if you'd prefer me to not do that though, and I can change the way I make commits.

**Comment by jacobdaddario** [comment]
Resolves #12

**Comment by joemasilotti** [comment]
Awesome! I'll dig into this today.

Do whatever works for you with the commit history. During merge, all of your commits will be squashed into a single merge commit anyways.

**Comment by joemasilotti** [comment]
Looks great! I made one commit that simplified a bunch of the markup for file uploads. Apparently you can use the `<label>` tag to trigger the native file upload without any JavaScript!

I'm going to add an issue to figure out default avatars and cover photos. There's a lot of `if` statements floating around the views right now.

**Pull request merged**
