### PR TITLE
Add basic twitter summary card.

### PR DESCRIPTION
**Pull request by pingortle**
This was a very quick take just to get something out there. Happy to make any changes desired.

Please let me know if you want any tests in particular.

#### No avatar
image

#### With avatar
image

Note: Twitter inherits og:title and og:description so there's no need to redefine them just for twitter.

/cc #37

### CODE REVIEW

**Comment by pingortle** [comment]
Hmmm… A developer's name should be in there somewhere… Maybe it's better to make the tw title their name and the tw description their hero?

@joemasilotti your call! Wdyt?

**Comment by joemasilotti** [comment]
No, this looks perfect (visually)! I'm purposely "hiding" names for now and want to expose the hero/description. Note how on the site you can't see the name, either. 

Will do a PR review today. Thanks for the contribution!

**Review by joemasilotti — CHANGES_REQUESTED** [review]
Would love to see this moved to a tested view component just for that little bit of logic for the avatar. 

Also, some devs might not have a Twitter so that shouldn't be rendered if blank.

**Comment by joemasilotti** [comment]
Please remove the string literal comment and standardize and I'll merge!

`bundle exec standardrb --fix`

**Comment by pingortle** [comment]
> Please remove the string literal comment and standardize and I'll merge!
> 
> `bundle exec standardrb --fix`

Hmmm… I might've been using an old global standard (via ale) instead of the bundled one.

Thanks for handling that! 🚀

**Comment by joemasilotti** [comment]
No problem! I also realized when I dove into the code that standard won't remove that comment. Nor "fix" the quotes in the tests because they use both quote types. TIL!

**Comment by joemasilotti** [comment]
FYI, I refactored this after realizing we need Open Graph tags for different pages.

https://github.com/joemasilotti/railsdevs.io/pull/68

**Pull request merged**
